# Generated by Django 5.0.4 on 2026-07-16 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("yoga", "Yoga"),
                            ("hiking", "Hiking"),
                            ("cycling", "Cycling"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organised_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
    ]
